# Font
font_family      DepartureMono Nerd Font
font_size        13.0

# Shell integration
shell_integration enabled
shell            /bin/bash

# Scrollback
scrollback_lines 10000

# Copy on select
copy_on_select yes

# Performance
repaint_delay    10
input_delay      3
sync_to_monitor  yes
